algoritmo "pgm01"
// Função : Exibir Nome, celular e cidade do desenvolvedor
// Autor : Lucas Pedroso Krzyzanowski
// Data : 20/01/2021
var

inicio
// Seção de Comandos 

   //Exibe na tela os dados de nome celular e cidade
   escreval("---- Identificacao do desenvolvedor ----")
   escreval()
   escreval ("Nome: Lucas Pedroso Krzyzanowksi")
   escreval ("Telefone: (41) 998450236")
   escreval ("Cidade: Araucária")

fimalgoritmo
