algoritmo "pgm36"
// Função : Atribuir valores e apresentar na tela
// Autor : Lucas Pedroso Krzyzanowski
// Data : 25/01/2021
var
   A, B: inteiro
inicio
// Seção de Comandos 

// cabeçalho
   escreval("---- Exercício de atribuição ----")
   escreval()
   
// atribuir valores as variaveis
   A <- 10
   B <- 20
// escreva na tela o valor de B
   escreval(B)

// atribuir novo valor a variavel B
   B <- 5

// escreva na tela o valor de A e B
   escreva (A, ", ",B)
fimalgoritmo
